WebClothing/Controllers/CategoryManageController.cs
using WebClothing.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebClothing.Controllers
{
    public class CategoryManageController : Controller
    {
        // GET: CategoryManage
        DBWebClothingEntities db = new DBWebClothingEntities();
        public ActionResult Index()
        {
            //if (CheckRole("Admin"))
            //{

            //}
            //else
            //{
            //    return
            //    RedirectToAction("Index", "Admin");
            //}

            var categories = db.Categories.ToList();
            return View(categories);
        }

        //public ActionResult ToggleActive(int ID)
        //{
        //    Category category = db.Categories.Find(ID);
        //    category.IsActive = !category.IsActive;
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        public ActionResult Details(int ID)
        {
            //if (CheckRole("Admin"))
            //{

            //}
            //else
            //{
            //    return RedirectToAction("Index", "Admin");
            //}
            Category category = db.Categories.Find(ID);
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            Category categoryUpdate = db.Categories.Find(category.ID);
            categoryUpdate.Name = category.Name;
            db.SaveChanges();
            ViewBag.Message = "Cập nhật thành công";
            return View("Details", categoryUpdate);
        }
        public ActionResult Edit()
        {
            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            //if (CheckRole("Admin"))
            //{

            //}
            //else
            //{
            //    return RedirectToAction("Index", "Admin");
            //}
            return View();
        }
        [HttpPost]
        public ActionResult Add(Category category)
        {
            //category.IsActive = true;
            Category cate = db.Categories.Add(category);
            db.SaveChanges();
            ViewBag.Message = "Thêm thành công";
            return RedirectToAction("Index");
        }
        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int? ID)
        {
            Category category = db.Categories.Find(ID);
            db.Categories.Remove(category);
            db.SaveChanges();
            ViewBag.Message = "Xoá thành công";
            return RedirectToAction("Index");
        }

    }
}

WebClothing/Views/CategoryManage/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Category</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="/CategoryManage/Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Category</a>
            <span class="breadcrumb-item active">Tạo mới Category</span>
        </nav>
    </div>
</div>
<div class="page-header no-gutters has-tab">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
        </li>
    </ul>
</div>
<div class="tab-content m-t-15">
    <div class="tab-pane fade show active" id="product-edit-basic">
        <div class="card">
            @using (Html.BeginForm("Add", "CategoryManage", FormMethod.Post))
            {
                <div class="card-body">
                    <div class="form-group">
                        <label>Tên</label>
                        <input type="text" class="form-control" placeholder="Category" name="Name">
                    </div>
                </div>
                <div class="card-footer">
                    <a href="/CategoryManage/" class="btn btn-light-secondary">Trở lại</a>
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            }
        </div>
    </div>
</div>

WebClothing/Views/CategoryManage/Delete.cshtml
@model WebClothing.Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Bạn có thật sự muốn xoá?</h3>
<div>

    @using (Html.BeginForm("Delete", "CategoryManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <div class="card-footer">
            <a href="/CategoryManage/" class="btn btn-light-secondary">Trở lại</a>
            <button type="submit" class="btn btn-danger ml-1">Xoá</button>
        </div>
    }
</div>

WebClothing/Views/CategoryManage/Details.cshtml
@model WebClothing.Models.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Products</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="/Category/Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Danh sách Category</a>
            <span class="breadcrumb-item active">Chi tiết</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
                <img src="~/Content/assets/images/others/thumb-16.jpg" alt="">
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Name</h4>
                <p class="text-muted m-b-0">Code: #@Model.ID</p>
            </div>
        </div>
        <div class="m-b-15">
            <a href="@Url.Action("Edit", new { id = Model.ID })" class="btn btn-primary">
                <i class="anticon anticon-edit"></i>
                <span>Sửa</span>
            </a>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">Tổng quan</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Thông Tin</h4>
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>ID:</td>
                                    <td class="text-dark font-weight-semibold">@Model.ID</td>
                                </tr>
                                <tr>
                                    <td>Tên Category:</td>
                                    <td>	@Model.Name </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Chỉnh sửa</h3>
                    </div>
                    @using (Html.BeginForm("Edit", "CategoryManage", FormMethod.Post))
                    {
                        <input type="text" name="ID" value="@Model.ID" hidden />
                        <div class="card-body">
                            <span class="badge bg-success">@ViewBag.Message</span>
                            <div class="form-group">
                                <label>Tên</label>
                                <input type="text" class="form-control" value="@Model.Name" required name="Name">
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <a href="/CategoryManage/" class="btn btn-light-secondary">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

WebClothing/Views/CategoryManage/Index.cshtml
@model List<WebClothing.Models.Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Products</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="/CategoryManage/Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Category</a>
            <span class="breadcrumb-item active">Danh sách Category</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Catergory</option>
                            <option value="all">All</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-right">
                <a href="/CategoryManage/Add" class="btn btn-primary">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Tạo mới</span>
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên Category</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                #@item.ID
                            </td>
                            <td>
                                @item.Name
                            </td>

                            <td class="text-right">
                                <a href="@Url.Action("Details", new { id = item.ID })" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                    <i class="anticon anticon-info"></i>
                                </a>
                                
                                <a href="@Url.Action("Delete", new { id = item.ID })" class="btn btn-icon btn-hover btn-sm btn-rounded pull-right">
                                    <i class="anticon anticon-delete"></i>
                                </a>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>