WebClothing/Controllers/ProductManageController.cs
using WebClothing.Models;
using PagedList;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;

namespace WebClothing.Controllers
{
    public class ProductManageController : Controller
    {
        // GET: ProductManage
        DBWebClothingEntities db = new DBWebClothingEntities();

        public ActionResult Index(int CategoryID = 0, string keyword = "", int? page = 1)
        {
            //if (CheckRole("Admin"))
            //{

            //}
            //else
            //{
            //    return RedirectToAction("Index", "Admin");
            //}

            List<Product> products = new List<Product>();
            if (keyword != "")
            {
                products = db.Products.Where(x => x.Name.Contains(keyword)).OrderBy(x => x.ID).ToList();
            }
            if (CategoryID != 0)
            {
                ViewBag.NamePage = "Category " + db.Categories.Find(CategoryID).Name;
                ViewBag.ListProduct = db.Products.Where(x => x.IsActive == true && x.CategoryID == CategoryID).ToList();
            }
            else
            {
                products = db.Products.Where(x => x.Name.Contains(keyword)).OrderBy(x => x.ID).ToList();
            }
            //Phân trang
            if (page == null) page = 1;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            //int pageNumber = page;
            PagedList<Product> models = new PagedList<Product>(products.AsQueryable(), pageNumber, pageSize);

            //Trang hiện tại
            ViewBag.CurrentPage = pageNumber;
            return View(models);

        }

        public ActionResult Details(int ID)
        {
            //if (CheckRole("Admin"))
            //{

            //}
            //else
            //{
            //    return RedirectToAction("Index", "Admin");
            //}
            Product product = db.Products.Find(ID);
            ViewBag.CategoryList = db.Categories.ToList();
            return View(product);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Product product, HttpPostedFileBase[] ImageUpload)
        {
            Product productUpdate = db.Products.Find(product.ID);
            productUpdate.Name = product.Name;
            productUpdate.Price = product.Price;
            productUpdate.Quantity = product.Quantity;
            //productUpdate.Type = product.Type;
            productUpdate.CategoryID = product.CategoryID;
            productUpdate.Description = product.Description;

            for (int i = 0; i < ImageUpload.Length; i++)
            {
                //Check content image
                if (ImageUpload[i] != null && ImageUpload[i].ContentLength > 0)
                {
                    //Get file name
                    var fileName = Path.GetFileName(ImageUpload[i].FileName);
                    //Get path
                    var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    //Check exitst
                    if (!System.IO.File.Exists(path))
                    {
                        //Add image into folder
                        ImageUpload[i].SaveAs(path);
                    }
                }
            }

            if (ImageUpload[0] != null)
            {
                productUpdate.Image1 = ImageUpload[0].FileName;
            }
            //if (ImageUpload[1] != null)
            //{
            //    productUpdate.Image2 = ImageUpload[1].FileName;
            //}
            //if (ImageUpload[2] != null)
            //{
            //    productUpdate.Image3 = ImageUpload[2].FileName;
            //}
            db.SaveChanges();

            ViewBag.CategoryList = db.Categories.ToList();
            ViewBag.Message = "Cập nhật thành công";
            return View("Details", productUpdate);
        }
        public ActionResult Edit()
        {
            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            //if (CheckRole("Admin"))
            //{

            //}
            //else
            //{
            //    return RedirectToAction("Index", "Admin");
            //}
            ViewBag.CategoryList = db.Categories.ToList();
            return View();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Add(Product product, HttpPostedFileBase[] ImageUpload)
        {
            for (int i = 0; i < ImageUpload.Length; i++)
            {
                //Check content image
                if (ImageUpload[i] != null && ImageUpload[i].ContentLength > 0)
                {
                    //Get file name
                    var fileName = Path.GetFileName(ImageUpload[i].FileName);
                    //Get path
                    var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    //Check exitst
                    if (!System.IO.File.Exists(path))
                    {
                        //Add image into folder
                        ImageUpload[i].SaveAs(path);
                    }
                }
            }

            if (ImageUpload[0] != null)
            {
                product.Image1 = ImageUpload[0].FileName;
            }
            //if (ImageUpload[1] != null)
            //{
            //    product.Image2 = ImageUpload[1].FileName;
            //}
            //if (ImageUpload[2] != null)
            //{
            //    product.Image3 = ImageUpload[2].FileName;
            //}
            //product.CreatedBy = (Session["User"] as Models.User).ID;
            //product.ViewCount = 0;
            //product.PurchasedCount = 0;
            product.IsActive = true;
            db.Products.Add(product);
            db.SaveChanges();
            ViewBag.CategoryList = db.Categories.ToList();
            ViewBag.Message = "Thêm thành công";
            return RedirectToAction("Index");
        }

        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int? ID)
        {
            Product product = db.Products.Find(ID);
            db.Products.Remove(product);
            db.SaveChanges();
            ViewBag.Message = "Xoá thành công";
            return RedirectToAction("Index");
        }
    }
}

WebClothing/Views/ProductManage/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    List<WebClothing.Models.Category> categoryies = ViewBag.CategoryList as List<WebClothing.Models.Category>;
}

<div class="page-header">
    <h2 class="header-title">Product</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="/Product/Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Product</a>
            <span class="breadcrumb-item active">Tạo mới Product</span>
        </nav>
    </div>
</div>
@using (Html.BeginForm("Add", "ProductManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <form>
        <div class="page-header no-gutters has-tab">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="inputState">Tên sản phẩm</label>
                            <input type="text" class="form-control" required name="Name">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="inputState">Danh mục</label>
                            <select name="CategoryID" class="form-control">
                                    @foreach (var item in categoryies)
                                    {
                                        <option value="@item.ID">@item.Name</option>
                                    }
                                </select>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="inputState">Giá sản phẩm</label>
                            <input type="text" class="form-control" required name="Price">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="inputState">Số lượng</label>
                            <input type="text" class="form-control" required name="Quantity">
                        </div>
                        @*<div class="form-group">
                            <label class="font-weight-semibold">Trạng thái</label>
                            <select class="custom-select" name="Status">
                                <option value="0">Có sẵn</option>
                                <option value="1">Hết hàng</option>
                            </select>
                        </div>*@
                    <div class="form-group">
                        <label class="font-weight-semibold" for="inputState">Mô tả</label>
                        <textarea class="form-control" id="mytextarea" required name="Description"> </textarea>
                    </div>
                    <div class="form-group">
                        <label>Chọn hình 1 (*)</label>
                        <input type="file" class="form-control" name="ImageUpload" required>
                    </div>
                    </div>
                    <div class="form-group">
                        <div class=" col-12 ">
                            <a href="/ProductManage/" class="btn btn-default">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </form>
}

WebClothing/Views/ProductManage/Delete.cshtml
@model WebClothing.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h1>Bạn có thật sự muốn xoá?</h1>
<div>

    @using (Html.BeginForm("Delete", "ProductManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <div class="card-footer">
            <a href="/ProductManage/" class="btn btn-light-secondary">Trở lại</a>
            <button type="submit" class="btn btn-danger ml-1">Xoá</button>
        </div>
    }
</div>

WebClothing/Views/ProductManage/Details.cshtml
@model WebClothing.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    List<WebClothing.Models.Category> categories = ViewBag.CategoryList as List<WebClothing.Models.Category>;
}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="alert alert-primary">
                        <i class="bi bi-star"></i> @Model.Name
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("Edit", "ProductManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        <input type="text" name="ID" value="@Model.ID" hidden />
                        <div class="card-body">
                            <span class="badge bg-success">@ViewBag.Message</span>
                            <div class="form-group">
                                <label>Tên</label>
                                <input type="text" class="form-control" value="@Model.Name" required name="Name">
                            </div>
                            <div class="form-group">
                                <label>Danh mục</label>
                                <select name="CategoryID" class="form-control">
                                    @foreach (var item in categories)
                                    {
                                        if (item.ID == Model.CategoryID)
                                        {
                                            <option value="@item.ID" selected>@item.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@item.ID">@item.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Đơn giá</label>
                                <input type="text" class="form-control" value="@Model.Price.Value" required name="Price">
                            </div>
                            <div class="form-group">
                                <label>Số lượng</label>
                                <input type="text" class="form-control" value="@Model.Quantity" required name="Quantity">
                            </div>
                            @*<div class="form-group">
                                <label>Phù hợp với: </label>
                                <input type="text" class="form-control" value="@Model.Type" required name="Type">
                            </div>
                            <div class="form-group">
                                <label>Lượt xem</label>
                                <input type="text" class="form-control" value="@Model.ViewCount" required name="ViewCount" disabled>
                            </div>
                            <div class="form-group">
                                <label>Đã bán</label>
                                <input type="text" class="form-control" value="@Model.PurchasedCount" required name="PurchasedCount" disabled>
                            </div>*@
                            <div class="form-group">
                                <label>Hình 1</label>
                                <img src="~/Content/images/@Model.Image1" alt="Alternate Text" style="width:15%;height:15%;border: solid 1px gray" />
                                @*<label>Hình 2</label>
                                <img src="~/Content/images/@Model.Image2" alt="Alternate Text" style="width:15%;height:15%;border: solid 1px gray" />
                                <label>Hình 3</label>
                                <img src="~/Content/images/@Model.Image3" alt="Alternate Text" style="width:15%;height:15%;border: solid 1px gray" />*@
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 1 mới</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            @*<div class="form-group">
                                <label>Chọn hình 2 mới</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 3 mới</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>*@
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea class="form-control" required id="mytextarea" name="Description">@Model.Description</textarea>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <a href="/ProductManage/" class="btn btn-light-secondary">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

WebClothing/Views/ProductManage/Index.cshtml
@using PagedList.Mvc
@using PagedList
@model IPagedList<WebClothing.Models.Product>

@{ int CurrentPage = ViewBag.CurrentPage;
    ViewBag.Title = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }
<div class="page-header">
    <h2 class="header-title">Products</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Products</a>
            <span class="breadcrumb-item active">Danh sách Producst</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Catergory</option>
                            <option value="all">All</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-right">
                <a href="/ProductManage/Add" class="btn btn-primary">
                    <i class="anticon anticon-plus-circle m-r-5"></i>

                    <span>Add Product</span>
                </a>
            </div>
        </div>
       
            <div class="table-responsive">
                <table class="table table-hover e-commerce-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Product</th>
                            <th>Category</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                          {
                            <tr>
                                <td>
                                    #@item.ID
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img class="img-fluid rounded" src="~/Content/Images/@item.Image1" style="max-width: 60px" alt="">
                                        <h6 class="m-b-0 m-l-10">@item.Name</h6>
                                    </div>
                                </td>
                                <td>@item.Category.Name</td>
                                <td>
                                    @item.Price.Value.ToString("#,##")₫
                                </td>

                                <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                                <td class="text-right">
                                    <a href="@Url.Action("Details", new { id = item.ID })" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-info"></i>
                                    </a>
                                    <a href="@Url.Action("Delete", new { id = item.ID })" class="btn btn-icon btn-hover btn-sm btn-rounded pull-right">
                                        <i class="anticon anticon-delete"></i>
                                    </a>

                                </td>
                            </tr>
                            }
                    </tbody>
                </table>
            </div>

    </div>
</div>